### PR TITLE
compatibility with GPaste 3.18

### PR DESCRIPTION
**Pull request by Elemag**
Sorry but I don't have the resources and willingness to fix multiple histories :)

### CODE REVIEW

**Comment by deekej** [comment]
Works fine, please consider merging and creating new version. Thank you! :)

**Comment by Feuerfuchs** [comment]
Sorry about the delay, the last semester was busy as hell. x.x I just merged your fix and will test it in the next few days.

**Comment by Feuerfuchs** [comment]
Alright, I tested it and added some more improvements to add support for GPaste 3.20. Thanks a lot for your contribution, @Elemag  ! :)

**Comment by Elemag** [comment]
Great!
Updating now.

**Comment by Elemag** [comment]
Hm, seems not to be working on my side:
No JS module 'GPasteHistoryListItem' found in search path.

**Comment by Feuerfuchs** [comment]
Weird, I used "git commit -am" to automatically add new files, but it didn't work apparently. I added the missing file now.

**Comment by Elemag** [comment]
Much better :)

**Pull request merged**
